image:
  repository: ghcr.io/martinvasseur-lab/helm-deployment
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

deployment:
  name: helm-deployment
  label: helm
  container: 
    name: helm

service:
  name: helm-service
  type: ClusterIP
  port: 3000

