apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-deployment
  labels:
    app: {{ }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/martinvasseur-lab/kargo-project
        ports:
        - containerPort: 80