apiVersion: apps/v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec: 
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.label }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}

